version = 0.1


[development-a.deploy.parameters]
stack_name = "ipv-passport-back-development-a"
s3_bucket = "di-ipv-cri-lambda-artifact-bucket"
s3_prefix = "passport-back-development-a"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"development-a\""
parallel = "true"

[development-b.deploy.parameters]
stack_name = "ipv-passport-back-development-b"
s3_bucket = "di-ipv-cri-lambda-artifact-bucket"
s3_prefix = "passport-back-development-b"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"development-b\""
parallel = "true"

[development-c.deploy.parameters]
stack_name = "ipv-passport-back-development-c"
s3_bucket = "di-ipv-cri-lambda-artifact-bucket"
s3_prefix = "passport-back-development-c"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"development-c\""
parallel = "true"

[dev-tom.deploy.parameters]
stack_name = "tom-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "tom-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-tom\""

[dev-danh.deploy.parameters]
stack_name = "danh-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danh-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danh\""

[dev-danw.deploy.parameters]
stack_name = "danw-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danw-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danw\""

[dev-danp.deploy.parameters]
stack_name = "danp-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danp-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danp\""

[dev-chris.deploy.parameters]
stack_name = "chris-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "chris-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-chris\""

[dev-amrit.deploy.parameters]
stack_name = "amrit-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "amrit-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-amrit\""

[dev-lai.deploy.parameters]
stack_name = "lai-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "lai-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-lai\""

[dev-sunil.deploy.parameters]
stack_name = "sunil-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "sunil-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-sunil\""

[dev-kerr.deploy.parameters]
stack_name = "kerr-ipv-cri-uk-passport-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "kerr-ipv-cri-uk-passport-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-kerr\""

